### PR TITLE
Add kaufhaus layouts

### PR DESCRIPTION
**Pull request by SSirjes**
Closes: #131

### CODE REVIEW

**Comment by SSirjes** [comment]
* [ ] fix product 'is-cropped' position
* [ ] fix product 'delete' image icon position

**Comment by SSirjes** [comment]
* [ ] If root item is product list, where product related layouts are hidden in main menu, then common page subpage shows product related menu items in main menu

**Comment by siimha** [comment]
* [ ] No content area in product list layout
screen shot 2018-07-05 at 09 48 14

**Comment by siimha** [comment]
* [ ] Form field has two select icons in IE11

field select

**Comment by SSirjes** [comment]
* [ ] don't display empty submenu

**Pull request merged**
